version: '3.9'

x-base_service: &base_service
    volumes:
      - &v1 ${WEBUI_DATA_PATH:-./data}:/data
      - &v2 ${WEBUI_OUTPUT_PATH:-./output}:/output
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto", "auto-sygil", "all"]
    ports:
      - "${WEBUI_AUTOMATIC_PORT:-7860}:7860"
    restart: unless-stopped
    build:
      context: ./services/AUTOMATIC1111
      args:
        - SHA=${AUTO_SHA}
    image: sd-auto:49
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  invoke:
    <<: *base_service
    profiles: ["invoke", "auto-invoke", "all"]
    ports:
      - "${WEBUI_INVOKE_PORT:-7861}:7860"
    restart: unless-stopped
    build:
      context: ./services/invoke
      args:
        - SHA=${INVOKE_SHA}
    image: sd-invoke:26
    environment:
      - PRELOAD=true
      - CLI_ARGS=


  sygil: &sygil
    <<: *base_service
    profiles: ["sygil"]
    ports:
      - "${WEBUI_SYGIL_PORT:-7862}:7860"
    restart: unless-stopped
    build:
      context: ./services/sygil
      args:
        - SHA=${SYGIL_SHA}
    image: sd-sygil:16
    environment:
      - CLI_ARGS=--optimized-turbo
      - USE_STREAMLIT=0

  sygil-sl:
    <<: *sygil
    profiles: ["sygil-sl", "auto-sygil", "all"]
    environment:
      - USE_STREAMLIT=1
